version: "3"

services:
  shardsvr8_1:
    container_name: shardsvr8_1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard8_rs --dbpath /data/db --port 27017
    ports:
      - 20022:27017
    volumes:
      - shardsvr8_1:/data/db

  shardsvr8_2:
    container_name: shardsvr8_2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard8_rs --dbpath /data/db --port 27017
    ports:
      - 20023:27017
    volumes:
      - shardsvr8_2:/data/db

  shardsvr8_3:
    container_name: shardsvr8_3
    image: mongo:latest
    command: mongod --shardsvr --replSet shard8_rs --dbpath /data/db --port 27017
    ports:
      - 20024:27017
    volumes:
      - shardsvr8_3:/data/db

volumes:
  shardsvr8_1:
  shardsvr8_2:
  shardsvr8_3:

networks:
  default:
    external:
      name: mongodb_network
