version: '3'

services:
  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb config_rs/configsvr1:27017,configsvr2:27017,configsvr3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 30000:27017
    networks:
      - mongodb_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "${MONGO_ROOT_PASSWORD}", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always

    

networks:
  mongodb_network:
    external: true